name: Build Project

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Rust toolchain
      uses: actions/toolchain@v1
      with:
        toolchain: stable
        profile: minimal

    - name: Build release
      run: cargo build --release --verbose

    - name: Run tests
      run: cargo test --verbose

    - name: Upload artifact (Linux)
      if: matrix.os == 'ubuntu-latest'
      uses: actions/upload-artifact@v4
      with:
        name: xlsx-trimmer-linux
        path: target/release/xlsx-trimmer

    - name: Upload artifact (Windows)
      if: matrix.os == 'windows-latest'
      uses: actions/upload-artifact@v4
      with:
        name: xlsx-trimmer-windows
        path: target/release/xlsx-trimmer.exe
